### ISSUE TITLE
About parallel computing error and implement of gravity term

### ISSUE THREAD

**Issue by senlinq** [MartinKotoucSourek/openHFDIB-DEM#4]
Thanks for your wonderful code, which I have learned a lot from.
I would like to use your tools for the numerical simulation for the sedimentation of a large number of particles in the flow field (for instance, water). 
However, I encountered a problem:

 I would like to simulate particle settling in **_2D_** using **_dynamic refine mesh_** in parallel run, what would be the **_appropriate boundary conditions_** and **_fvSolution_** setup? I noticed that some examples of boundary conditions are given in the tutorial, which make me confused. With the setup in my own test case, the simulation in single core can be successfully completed (see run.log). **_However, when run in parallel, the simulation quickly diverges when the particle is about to hit the wall (see run_parallel.log)._** How to fix this problem?
[case.zip](https://github.com/MartinKotoucSourek/openHFDIB-DEM/files/9712634/case.zip)

**Comment by MartinKotoucSourek** [comment]
Dear senlin,

I appreciate your interest in our code. First I would like to ask you to leave the issue page for the bugs (the point 2 of your post for example) and move the questions to discusion page.

1) It is common approach to add gravity term directly into the Ueqn, however I feel your point and found out that the gravity can be added to the equation using fvOptions, therefore we will remove this term in the following 2.3 version. Thank you. For your purpose you can do it manually by yourself before we release the new version.

2) This is tricky. I tried to investigate this problem and it looks like the error originate in DILUPBiCG class. The problem is in solution of the fluid velocity in z-direction. For me it looks like the combination of the 2D domain, decomposition in the center of z-axis and no-slip BC at the bottom of the domain. I made it works when the BC for the bottom to slipbut I know that this is not what your are looking for. I wrote the bug to our system and we will look at it. 

3) It depends how well the fluid field should be resolved. However, there is no minimal number of the nOuterCorrectors besides the standard CFD recommendations. The value originate in "Bruno Blais, Manon Lassaigne, Christoph Goniva, Louis Fradette, François Bertrand, A semi-implicit immersed boundary method and its application to viscous mixing, Computers & Chemical Engineering". It is a relaxation factor that should be in (0, 0.9]. We found out that 0.8 works well for us, but it is true that it should be moved out to the configuration file in order to be specified by the user.

**Comment by senlinq** [comment]
> Dear senlin,
> 
> I appreciate your interest in our code. First I would like to ask you to leave the issue page for the bugs (the point 2 of your post for example) and move the questions to discusion page.
> 
> 1. It is common approach to add gravity term directly into the Ueqn, however I feel your point and found out that the gravity can be added to the equation using fvOptions, therefore we will remove this term in the following 2.3 version. Thank you. For your purpose you can do it manually by yourself before we release the new version.
> 2. This is tricky. I tried to investigate this problem and it looks like the error originate in DILUPBiCG class. The problem is in solution of the fluid velocity in z-direction. For me it looks like the combination of the 2D domain, decomposition in the center of z-axis and no-slip BC at the bottom of the domain. I made it works when the BC for the bottom to slipbut I know that this is not what your are looking for. I wrote the bug to our system and we will look at it.
> 3. It depends how well the fluid field should be resolved. However, there is no minimal number of the nOuterCorrectors besides the standard CFD recommendations. The value originate in "Bruno Blais, Manon Lassaigne, Christoph Goniva, Louis Fradette, François Bertrand, A semi-implicit immersed boundary method and its application to viscous mixing, Computers & Chemical Engineering". It is a relaxation factor that should be in (0, 0.9]. We found out that 0.8 works well for us, but it is true that it should be moved out to the configuration file in order to be specified by the user.

Thanks for your reply. Sorry for the misunderstanding of the page. I will leave point 2 for issue page, and move point 1 and point 3 to discussion soon. And I still have some questions about your answer:

1. Is it correct from the point of equation and simulation, **_if **_I just remove the gravity term in Ueqn and do not add it to fvOptions_**?_** The reason is that the effect of gravity is already shown in the force on the particle. 

2. I appreciate for your detailed explanation. And I found it is possible to run 2D simulation (with empty B.C.) in parallel run by choosing another iteration method, without using dynamic refine mesh. However, it has caused lager **_time step continuity errors_** than running in single core. Based on your published article, **_it seems this issue does not affect 3D simulation using dynamic refine mesh in parallel run?_**

3. Thanks again for your careful explanation and time.

**Comment by MartinKotoucSourek** [comment]
1. I think that it is perfectly ok as the gravity just increases the hydrostatic pressure inside the fluid. Therefore, it will have no effect on the result of the sedimentation.

2. Yes, we did not encounter such problem in 3D even using parallel run. However, I should mention that currently we work with dense cases and there is no need for dynamic refinement (it is cheaper to refine the whole domain because dynamic refinement is computationally expensive).
